targets::tar_test("tar_git_gitignore_unstash()", {
  tmp <- tempfile()
  dir.create(tmp)
  from <- file.path(tmp, ".gitignore")
  to <- file.path(tmp, "gitignore_stash")
  writeLines("*", from)
  tar_git_gitignore_stash(tmp)
  expect_equal(readLines(from), tar_git_gitignore_lines())
  expect_equal(readLines(to), "*")
  tar_git_gitignore_unstash(tmp)
  expect_false(file.exists(file.path(tmp, "gitignore_stash")))
  expect_equal(readLines(from), "*")
})

targets::tar_test("tar_git_gitignore_restore(), stash .gitignore", {
  tmp <- tempfile()
  dir.create(tmp)
  from <- file.path(tmp, ".gitignore")
  to <- file.path(tmp, "gitignore_stash")
  writeLines("*", from)
  tar_git_gitignore_stash(tmp)
  tar_git_gitignore_restore(tmp)
  expect_equal(readLines(from), "*")
})

targets::tar_test("tar_git_gitignore_restore(), no .gitignore", {
  tmp <- tempfile()
  dir.create(tmp)
  from <- file.path(tmp, ".gitignore")
  to <- file.path(tmp, "gitignore_stash")
  writeLines("*", from)
  tar_git_gitignore_stash(tmp)
  unlink(from)
  tar_git_gitignore_restore(tmp)
  expect_equal(readLines(from), "*")
})
