# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, v2-branch]
  pull_request:
    branches: [main, master, v2-branch]

name: cover

jobs:
  cover:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./setup-r
        with:
          use-public-rspm: true

      - uses: ./setup-r-dependencies
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
